### PR TITLE
Improve instructions for local builds

### PR DESCRIPTION
**Pull request by WhyNotHugo**

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
I've tried `lektor server` but it's not working for me. I think some dependencies have incompatible versions:

```
> lektor server       
Traceback (most recent call last):
  File "/home/hugo/.local/state/virtualenvs/pimutils-meta/bin/lektor", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/hugo/.local/state/virtualenvs/pimutils-meta/lib/python3.11/site-packages/lektor/cli.py", line 621, in main
    cli.main(args=args, prog_name=name)
  File "/home/hugo/.local/state/virtualenvs/pimutils-meta/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/hugo/.local/state/virtualenvs/pimutils-meta/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugo/.local/state/virtualenvs/pimutils-meta/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugo/.local/state/virtualenvs/pimutils-meta/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugo/.local/state/virtualenvs/pimutils-meta/lib/python3.11/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugo/.local/state/virtualenvs/pimutils-meta/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hugo/.local/state/virtualenvs/pimutils-meta/lib/python3.11/site-packages/lektor/cli.py", line 336, in server_cmd
    from lektor.devserver import run_server
  File "/home/hugo/.local/state/virtualenvs/pimutils-meta/lib/python3.11/site-packages/lektor/devserver.py", line 9, in <module>
    from lektor.admin import WebAdmin
  File "/home/hugo/.local/state/virtualenvs/pimutils-meta/lib/python3.11/site-packages/lektor/admin/__init__.py", line 1, in <module>
    from .webui import WebAdmin
  File "/home/hugo/.local/state/virtualenvs/pimutils-meta/lib/python3.11/site-packages/lektor/admin/webui.py", line 6, in <module>
    from flask import abort
  File "/home/hugo/.local/state/virtualenvs/pimutils-meta/lib/python3.11/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/home/hugo/.local/state/virtualenvs/pimutils-meta/lib/python3.11/site-packages/jinja2/__init__.py)
```

**Comment by untitaker** [comment]
we should get rid of it entirely. lektor does not care about working with recent python dependencies, and i had major issues trying to pin flask/jinja/werkzeug to the right old versions.

**Comment by WhyNotHugo** [comment]
Remove it was my first though, but I though I'd try and give it a chance first.

I'll drop this PR and simply replace it entirely.

**Comment by untitaker** [comment]
I would recommend it at least. I already spent too much time trying to find the right pins, and lektor is unmaintained anyway

**Pull request closed without merging**
